FROM node:20.6.1 as builder
COPY ./package.json ./package-lock.json ./
RUN npm install


FROM node:20.6.1 as runner

# Copy in all the dependencies we need, by avoiding
# installing them in this stage, we prevent Yarn
# from including additional cache files, which
# yields a slimmer image.
COPY                ./package-lock.json  ./
COPY --from=builder ./node_modules/ ./node_modules/
COPY . .
EXPOSE 8080
CMD ["npm", "start"]